### PR TITLE
Role based access

### PR DESCRIPTION
**Pull request by NikitaGandhi**
This work is done to support role/session based access to AWS resources rather than passing AWS credentials to pod. This will require few changes to your deployment template as well along with this app level change to get a temporary creds using assume role with web identity token. 

Note: This change can address the issue to support large scale processing job using kube2iam role. 

**Not an urgent change. we will merge when we have a time for test this new feature.**

**How to test:**

update the kubernetes alchemist processing deployment template:

- Create a service-role with required policies and trusted policy attached to it (**automated using terraform deployment)

- Add service-account to template: 
```
---
# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alchemist-processor-sa
  namespace: alchemist-processor
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::060378307146:role/<role-name>
```

- Associate role to pod deployment spec using:
`serviceAccountName: alchemist-processor-sa`

- Remove credentials from container env variables

### CODE REVIEW

**Comment by omad** [comment]
Looks cool!

We can add `assume_role_helper` into the top level module, it's not necessary to create the `helper` module for a single file.

I think it would be nicer to wrap up the deciding whether to use an autorefreshing session, and initialising it from env variables into a function too, rather than copying the same 10ish lines of code into multiple spots.

**Comment by NikitaGandhi** [comment]
Thanks Damien! 
Made changes accordingly.

**Comment by alexgleith** [comment]
Is this still relevant, @NikitaGandhi?

**Comment by alexgleith** [comment]
Sorry, I think I understand it a bit better now. Still needs testing...

**Comment by NikitaGandhi** [comment]
We tried and tested this setup in lccs processing job

**Pull request closed without merging**
