### PR TITLE
add sys.exit if no message in queue

### PR DESCRIPTION
**Pull request by pindge**
addressing https://github.com/opendatacube/datacube-alchemist/issues/93

### CODE REVIEW

**Comment by alexgleith** [comment]
I don't think it is an error if there's no messages on the queue.

And I'm not sure you can compare a generator to `0` either, that doesn't make sense.

Are you sure that the problem is that the queue is empty? Is it perhaps Keda not scaling down to zero pods?

**Comment by alexgleith** [comment]
Also, exiting with `1` will just change where the crash happens, won't it?

**Comment by alexgleith** [comment]
I think you're better off exiting with success in the `run_from_queue` command. Which... doesn't it already do that?

**Comment by pindge** [comment]
> I don't think it is an error if there's no messages on the queue.
> 
> And I'm not sure you can compare a generator to `0` either, that doesn't make sense.
> 
> Are you sure that the problem is that the queue is empty? Is it perhaps Keda not scaling down to zero pods?

```
(base) ubuntu@dea-dev-eks:~/datacube-explorer$ kg hpa -n processing
+ kubectl get hpa -n processing
NAME                                         REFERENCE                                   TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
airflow-worker                               StatefulSet/airflow-worker                  74%/80%             5         16        7          39d
keda-hpa-alchemist-c3-processing-fc-so       Deployment/alchemist-c3-processing-fc       <unknown>/1 (avg)   1         20        0          13d
keda-hpa-alchemist-c3-processing-wo-so       Deployment/alchemist-c3-processing-wo       <unknown>/1 (avg)   1         20        0          13d
keda-hpa-alchemist-s2-nrt-processing-bs-so   Deployment/alchemist-s2-nrt-processing-bs   4375m/5 (avg)       1         20        8          13d
keda-hpa-alchemist-s2-nrt-processing-wo-so   Deployment/alchemist-s2-nrt-processing-wo   5700m/5 (avg)       1         20        20         13d
keda-hpa-alchemist-s2-processing-wo-so       Deployment/alchemist-s2-processing-wo       5/5 (avg)           1         20        2          13d
```

From keda doc

```
For the purposes of scaling, "actual messages" is equal to ApproximateNumberOfMessages + ApproximateNumberOfMessagesNotVislble, since NotVisible in SQS terms means the message is still in-flight/processing.
```

The queue was empty however there were inflight -messages in the queue

**Comment by alexgleith** [comment]
Isn't exiting with success the best thing to do here then?

**Comment by pindge** [comment]
> I don't think it is an error if there's no messages on the queue.
> 
> And I'm not sure you can compare a generator to `0` either, that doesn't make sense.
> 
> Are you sure that the problem is that the queue is empty? Is it perhaps Keda not scaling down to zero pods?



> Isn't exiting with success the best thing to do here then?

i dont know how lol, so i just copied a bit of code from another section.

**Comment by alexgleith** [comment]
Sorry, I don't think this fixes the issue and I don't think we do want to exit here if there's nothing on the queue.

**Pull request closed without merging**
