### PR TITLE
Fix xarray issue. Xarray MUSt be <=0.16.1

### PR DESCRIPTION
**Pull request by alexgleith**

### CODE REVIEW

**Review by fangfy — APPROVED** [review]
Hope this fixes the issue... for now...

**Comment by woodcockr** [comment]
What was wrong with Xarray > 0.16.1??

**Comment by alexgleith** [comment]
It does something different with how it passes through attributes, so FC and WOfS implementations need to be upgrade to support later versions of xarray.

**Comment by alexgleith** [comment]
The result is that areas outside the scene extent are no longer nodata, they're ... messy data!

**Comment by alexgleith** [comment]
Note here for @emmaai 

Producing an FC scene on this dataset: `s3://deafrica-landsat/collection02/level-2/standard/oli-tirs/2017/160/071/LC08_L2SP_160071_20170830_20200903_02_T1/*SR_stac.json`

Using the following steps in the Makefile:

* Run `make build`
* Run `make up`
* Run `make initdb`
* Run `make product-africa`
* Run `make index-africa`
* Run `make product-africa`

And if you remove the constraint of xarray==0.16.1 then the nodata areas outside the scene end up as black, so their not being recognised as nodata any more.

Image of results with xarray==0.16.1

image

Image of results with xarray==2022.3.0

image

**Comment by emmaai** [comment]
The problem lies with this line, https://github.com/GeoscienceAustralia/fc/blob/41c2869d6d14da6a78c1a8234aa86c6d70c720ce/fc/virtualproduct.py#L45
and hence this function 
https://github.com/GeoscienceAustralia/fc/blob/0fa096f287171689b8baad8f9dc59a752e0b87f5/fc/virtualproduct.py#L108

It has nothing to do with the fc algorithm and not used in DEA FC product.

**Comment by emmaai** [comment]
https://github.com/GeoscienceAustralia/fc/blob/0fa096f287171689b8baad8f9dc59a752e0b87f5/fc/virtualproduct.py#L101

It just shouldn't be `keep_attrs=True` if the `attrs` of `DataArray` are changed in the function, even I believe the intention was to keep the `attrs` of `DataSet`.

**Pull request merged**
