### PR TITLE
Fixes data filtering issues and mask output.

### PR DESCRIPTION
**Pull request by james-blitzm**

### CODE REVIEW

**Comment by james-blitzm** [comment]
@alexgleith Just minor changes to data filters. Intending to eventually refactor the transform implementation out of this repo and over to https://github.com/GeoscienceAustralia/nrt-predict/

**Review by alexgleith — APPROVED** [review]
Looks ok, I'm not sure this is the best way to mask nodata, but I don't have an alternative.

**Comment by james-blitzm** [comment]
> Looks ok, I'm not sure this is the best way to mask nodata, but I don't have an alternative.

I am planning to try using the contiguity band from S2 input to replace the -999 filters.

**Comment by alexgleith** [comment]
WOfS does it like this: https://github.com/GeoscienceAustralia/wofs/blob/master/wofs/filters.py

Not sure it's appropriate, as S-2 might have different masking.

**Pull request merged**
